services:
  - type: web
    name: license-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn license_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 